import type { Ingredient } from "./ingredient.type"

export const ingredientData: Ingredient[] = [
  {
    name: "151 proof rum",
    category: "base_spirit",
    abv: 75.5,
    baseSpiritGroup: "rum",
    flavorProfile: ["dry", "spicy"],
  },
  {
    name: "7-Up",
    category: "soft_drink",
    flavorProfile: ["sweet", "citrus"],
  },
  {
    name: "Absinthe",
    category: "base_spirit",
    abv: 68,
    baseSpiritGroup: "other",
    flavorProfile: ["herbal", "bitter"],
  },
  {
    name: "Absolut Citron",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "vodka",
    flavorProfile: ["citrus", "dry"],
  },
  {
    name: "Absolut Kurant",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "vodka",
    flavorProfile: ["fruity", "sweet"],
  },
  {
    name: "Absolut Vodka",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "vodka",
    flavorProfile: ["dry"],
  },
  {
    name: "Advocaat",
    category: "liqueur",
    abv: 15,
    flavorProfile: ["sweet", "creamy"],
  },
  {
    name: "Ale",
    category: "beer",
    abv: 5,
    flavorProfile: ["malty", "bitter"],
  },
  {
    name: "Amaretto",
    category: "liqueur",
    abv: 24,
    flavorProfile: ["sweet", "nutty"],
  },
  {
    name: "Añejo rum",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "rum",
    flavorProfile: ["spicy", "dry"],
  },
  {
    name: "Angelica root",
    category: "herb",
    flavorProfile: ["herbal", "bitter"],
  },
  {
    name: "Aperol",
    category: "aperitivo",
    abv: 11,
    flavorProfile: ["bitter", "sweet", "citrus"],
  },
  {
    name: "Apple brandy",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "brandy",
    flavorProfile: ["fruity", "dry"],
  },
  {
    name: "Apple cider",
    category: "other",
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Apple juice",
    category: "juice",
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Applejack",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "brandy",
    flavorProfile: ["fruity", "dry"],
  },
  {
    name: "Apricot brandy",
    category: "liqueur",
    abv: 30,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Bacardi Limon",
    category: "base_spirit",
    abv: 35,
    baseSpiritGroup: "rum",
    flavorProfile: ["citrus", "dry"],
  },
  {
    name: "Baileys irish cream",
    category: "liqueur",
    abv: 17,
    flavorProfile: ["sweet", "creamy", "chocolate"],
  },
  {
    name: "Banana liqueur",
    category: "liqueur",
    abv: 20,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Beer",
    category: "beer",
    abv: 5,
    flavorProfile: ["bitter"],
  },
  {
    name: "Berries",
    category: "fruit",
    flavorProfile: ["fruity", "sweet"],
  },
  {
    name: "Bitters",
    category: "liqueur",
    abv: 44,
    flavorProfile: ["bitter", "herbal"],
  },
  {
    name: "Black Sambuca",
    category: "liqueur",
    abv: 38,
    flavorProfile: ["sweet", "spicy"],
  },
  {
    name: "Blackberry brandy",
    category: "liqueur",
    abv: 30,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Blended Scotch",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "whiskey",
    flavorProfile: ["dry", "spicy"],
  },
  {
    name: "Blended whiskey",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "whiskey",
    flavorProfile: ["dry"],
  },
  {
    name: "Blue Curacao",
    category: "liqueur",
    abv: 25,
    flavorProfile: ["sweet", "citrus"],
  },
  {
    name: "Bourbon",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "whiskey",
    flavorProfile: ["sweet", "spicy"],
  },
  {
    name: "Brandy",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "brandy",
    flavorProfile: ["fruity", "dry"],
  },
  {
    name: "Cachaca",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "rum",
    flavorProfile: ["dry", "grassy"],
  },
  {
    name: "Campari",
    category: "aperitivo",
    abv: 24,
    flavorProfile: ["bitter", "herbal"],
  },
  {
    name: "Cantaloupe",
    category: "fruit",
    flavorProfile: ["fruity", "sweet"],
  },
  {
    name: "Carbonated water",
    category: "soft_drink",
    flavorProfile: ["mineral"],
  },
  {
    name: "Chambord raspberry liqueur",
    category: "liqueur",
    abv: 16.5,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Champagne",
    category: "wine",
    abv: 12,
    flavorProfile: ["dry", "fruity"],
  },
  {
    name: "Cherry brandy",
    category: "liqueur",
    abv: 30,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Cherry Heering",
    category: "liqueur",
    abv: 24,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Cherry Juice",
    category: "juice",
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Chocolate liqueur",
    category: "liqueur",
    abv: 20,
    flavorProfile: ["sweet", "chocolate"],
  },
  {
    name: "Coffee liqueur",
    category: "liqueur",
    abv: 20,
    flavorProfile: ["sweet", "coffee"],
  },
  {
    name: "Cognac",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "brandy",
    flavorProfile: ["dry", "fruity"],
  },
  {
    name: "Cointreau",
    category: "liqueur",
    abv: 40,
    flavorProfile: ["citrus", "sweet"],
  },
  {
    name: "Cranberry juice",
    category: "juice",
    flavorProfile: ["sour", "fruity"],
  },
  {
    name: "Dark rum",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "rum",
    flavorProfile: ["spicy", "sweet"],
  },
  {
    name: "Dry Vermouth",
    category: "fortified_wine",
    abv: 18,
    flavorProfile: ["dry", "herbal"],
  },
  {
    name: "Espresso",
    category: "coffee",
    flavorProfile: ["coffee", "bitter"],
  },
  {
    name: "Everclear",
    category: "base_spirit",
    abv: 95,
    baseSpiritGroup: "other",
    flavorProfile: ["dry"],
  },
  {
    name: "Frangelico",
    category: "liqueur",
    abv: 20,
    flavorProfile: ["sweet", "nutty"],
  },
  {
    name: "Gin",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "gin",
    flavorProfile: ["herbal", "dry"],
  },
  {
    name: "Grand Marnier",
    category: "liqueur",
    abv: 40,
    flavorProfile: ["citrus", "sweet"],
  },
  {
    name: "Green Chartreuse",
    category: "liqueur",
    abv: 55,
    flavorProfile: ["herbal", "sweet"],
  },
  {
    name: "Grenadine",
    category: "syrup",
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Guinness stout",
    category: "beer",
    abv: 4.2,
    flavorProfile: ["bitter", "coffee"],
  },
  {
    name: "Heavy cream",
    category: "dairy",
    flavorProfile: ["creamy"],
  },
  {
    name: "Irish whiskey",
    category: "base_spirit",
    abv: 40,
    baseSpiritGroup: "whiskey",
    flavorProfile: ["smooth", "dry"],
  },
  {
    name: "Jägermeister",
    category: "liqueur",
    abv: 35,
    flavorProfile: ["herbal", "sweet"],
  },
  {
    name: "Kahlua",
    category: "liqueur",
    abv: 20,
    flavorProfile: ["coffee", "sweet"],
  },
  {
    name: "Kiwi",
    category: "fruit",
    flavorProfile: ["sour", "fruity"],
  },
  // 추가
  {
    name: "Tequila",
    category: "base_spirit",
    abv: 40,
    flavorProfile: ["dry", "herbal"],
    baseSpiritGroup: "tequila",
  },
  {
    name: "Light Rum",
    category: "base_spirit",
    abv: 40,
    flavorProfile: ["sweet", "dry"],
    baseSpiritGroup: "rum",
  },
  {
    name: "Sweet Vermouth",
    category: "fortified_wine",
    abv: 16,
    flavorProfile: ["sweet", "herbal", "bitter"],
  },
  {
    name: "Triple Sec",
    category: "liqueur",
    abv: 30,
    flavorProfile: ["sweet", "citrus"],
  },
  {
    name: "Lemon Juice",
    category: "juice",
    flavorProfile: ["sour", "citrus"],
  },
  {
    name: "Lime Juice",
    category: "juice",
    flavorProfile: ["sour", "citrus"],
  },
  {
    name: "Angostura Bitters",
    category: "other",
    abv: 44,
    flavorProfile: ["bitter", "herbal", "spicy"],
  },
  {
    name: "Tonic Water",
    category: "soft_drink",
    flavorProfile: ["bitter", "sweet"],
  },
  {
    name: "Ginger Beer",
    category: "soft_drink",
    flavorProfile: ["spicy", "sweet"],
  },
  {
    name: "Mint",
    category: "herb",
    flavorProfile: ["herbal"],
  },
  {
    name: "Egg White",
    category: "dairy",
    flavorProfile: ["creamy"],
  },
  {
    name: "Orange Bitters",
    category: "other",
    abv: 40,
    flavorProfile: ["bitter", "citrus"],
  },
  {
    name: "Soda Water",
    category: "soft_drink",
    flavorProfile: ["dry"],
  },
  {
    name: "St. Germain",
    category: "liqueur",
    abv: 20,
    flavorProfile: ["sweet", "fruity", "herbal"],
  },
  {
    name: "Cinnamon",
    category: "spice",
    flavorProfile: ["spicy", "sweet"],
  },
  {
    name: "Honey",
    category: "syrup",
    flavorProfile: ["sweet"],
  },
  {
    name: "White Rum",
    category: "base_spirit",
    abv: 40,
    flavorProfile: ["sweet", "fruity"],
    baseSpiritGroup: "rum",
  },
  {
    name: "Spiced Rum",
    category: "base_spirit",
    abv: 35,
    flavorProfile: ["spicy", "sweet"],
    baseSpiritGroup: "rum",
  },
  {
    name: "Rye Whiskey",
    category: "base_spirit",
    abv: 45,
    flavorProfile: ["spicy", "dry"],
    baseSpiritGroup: "whiskey",
  },
  {
    name: "Maraschino Liqueur",
    category: "liqueur",
    abv: 32,
    flavorProfile: ["sweet", "fruity"],
  },
  {
    name: "Benedictine",
    category: "liqueur",
    abv: 40,
    flavorProfile: ["herbal", "sweet"],
  },
  {
    name: "Drambuie",
    category: "liqueur",
    abv: 40,
    flavorProfile: ["sweet", "herbal"],
  },
  {
    name: "Falernum",
    category: "liqueur",
    abv: 15,
    flavorProfile: ["spicy", "sweet", "citrus"],
  },

  // 🍋 Fruits
  {
    name: "Lime",
    category: "fruit",
    flavorProfile: ["sour", "citrus"],
  },
  {
    name: "Lemon",
    category: "fruit",
    flavorProfile: ["sour", "citrus"],
  },

  // 🧃 Juice
  {
    name: "Orange juice",
    category: "juice",
    flavorProfile: ["sweet", "citrus"],
  },
  {
    name: "Pineapple juice",
    category: "juice",
    flavorProfile: ["sweet", "fruity"],
  },
]
